format = """
[](surface0)\
$python\
$username\
[](bg:surface1 fg:surface0)\
$directory\
[](fg:surface1 bg:green)\
$git_branch\
$git_status\
[](fg:green bg:sapphire)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:sapphire bg:maroon)\
$docker_context\
[](fg:maroon bg:blue)\
$time\
[ ](fg:blue)\
\n$character"""

palette = "catppuccin_mocha"
command_timeout = 5000

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:red"
format = '[$user ]($style)'

[directory]
style = "bg:surface1 fg:text"
format = "[ $path ]($style)"
truncation_length = 5 
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:sapphire fg:base"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:teal fg:base"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:sapphire fg:base"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:sapphire fg:base"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:green fg:base"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:green fg:base"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:sapphire fg:base"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:sapphire fg:base"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:sapphire fg:base"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:sapphire fg:base"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:sapphire fg:base"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:sapphire fg:base"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:surface0 fg:text"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:sapphire fg:base"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:blue fg:base"
format = '[ $time ]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

